spring:
  application:
    name: mall-product
  cloud:
    nacos:
      config:
        server-addr: nacos-service.infrastructure.svc.cluster.local
        username: ${NACOS_USERNAME}
        password: ${NACOS_PASSWORD}
        namespace: ${NACOS_NAMESPACE}
        group: BASE
        refresh-enabled: true

  config:
    import:
      - nacos:mall-product-config.yaml

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health,info,metrics